# Config file for air (https://github.com/cosmtrek/air)
# Basic config for Gin project with main.go entry

[build]
  cmd = "go run ./cmd/api/main.go"
  bin = ""
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["vendor", "migrations"]
  exclude_file = []
  exclude_regex = []
  follow_symlink = false
  poll = false
  delay = 1000 # ms

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[debug]
  enable = false
  force_polling = false
  polling_interval = 1000

